---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "spire-server.fullname" . }}
  namespace: {{ include "spire-server.namespace" . }}
data:
  {{- if .Values.config }}
  server.conf: |
    {{ .Values.config | nindent 4 }}
  {{- end }}