---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.k8sWorkloadRegister.name }}-role
rules:
  - apiGroups: [ "authentication.k8s.io" ]
    resources: [ "tokenreviews" ]
    verbs: [ "get", "create" ]
  - apiGroups: [ "" ]
    resources: [ "endpoints", "nodes", "pods" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "spiffeid.spiffe.io" ]
    resources: [ "spiffeids" ]
    verbs: [ "create", "delete", "get", "list", "patch", "update", "watch" ]
  - apiGroups: [ "spiffeid.spiffe.io" ]
    resources: [ "spiffeids/status" ]
    verbs: [ "get", "patch", "update" ]
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "validatingwebhookconfigurations" ]
    verbs: [ "get", "list", "update", "watch" ]