---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "spire-server.fullname" . }}
  namespace: {{ include "spire-server.namespace" . }}
  labels:
    {{- include "spire-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "spire-server.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "spire-server.fullname" . }}
  template:
    metadata:
      namespace: {{ include "spire-server.namespace" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "spire-server.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "spire-server.serviceAccountName" . }}
      shareProcessNamespace: true
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- with .Values.image }}
          image: "{{ .repository }}:{{ .tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - -config
            - /run/spire/config/server.conf
          {{- with .Values.livenessProbe }}
          {{- if .enabled }}
          livenessProbe:
            httpGet:
              path: /live
              port: 8080
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          {{- if .enabled }}
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: {{ .initialDelaySeconds }}
            periodSeconds: {{ .periodSeconds }}
            timeoutSeconds: {{ .timeoutSeconds }}
            successThreshold: {{ .successThreshold }}
            failureThreshold: {{ .failureThreshold }}
          {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- if .Values.ports }}
          {{ .Values.ports | indent 10 }}
          {{- end }}
          {{- if .Values.volumes }}
          {{ .Values.volumes | indent 10 }}
          {{- end }}
        {{- with .Values.k8sWorkloadRegistrar }}
        - name: k8s-workload-registrar
          image: "{{ .image.repository }}:{{ .image.tag }}"
          {{- if .args }}
          {{ .args | nindent  10 }}
          {{- end }}
          {{- if .ports }}
          {{ .ports | nindent  10 }}
          {{- end }}
          {{- if .volumes }}
          {{ .volumes | nindent  10 }}
          {{- end }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podVolumes }}
      {{ .Values.podVolumes | indent 6 }}
      {{- end }}
  {{- if .Values.volumeClaimTemplates }}
  {{ .Values.volumeClaimTemplates | nindent  2 }}
  {{- end }}